# This is just the deployment. You may need more for RBAC.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.3
        args:
        - --source=ingress
        - --log-level=debug
        - --domain-filter=example.com
        - --provider=digitalocean
        # Needed with CNAMEs
        - --txt-prefix=_external-dns.
        env:
        - name: DO_TOKEN
          valueFrom:
            secretKeyRef:
              name: digitalocean
              key: DIGITALOCEAN_TOKEN
